### ISSUE TITLE
kube2iam fails to start on new node

### ISSUE THREAD

**Issue by denibertovic** [fpco/helm-charts#8]
This is most apparent when adding a new instance group where kube2iam will fail to start. The way to fix this is to fork the kube2iam chart and add this fix:

```
# This DaemonSet works around https://github.com/kubernetes/kops/issues/2685 by
# ensuring the 'cni0' interface is created (which won't happen until a
# non-hostNetwork pod is assigned to a node).
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube2iam-createcni0
  namespace: kube-system
  labels:
    app: kube2iam-createcni0
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: kube2iam-createcni0
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: sleep-forever
          image: gcr.io/google_containers/pause:0.8.0
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 10Mi
```
Obviously this would need to be fixed depending on the interface/networking we're using but given we're using `flannel-vxlan` on all of our clusters the interface in question is `cni0`. (At least I think this changes depending on the networking plugin used). 

Once fixed in our `local` chart we should switch to using that instead of the upstream chart. Would be nice to upstream the patch though.
